[package]
name = "day07-star1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
# petgraph = "0.5"
serde_json = "1.0.45"

[dependencies.petgraph]
version = "0.5"
features = ["serde-1"]
